name: client
description: A library for client-side MPC wallet operations.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  grpc: ^5.1.0
  protobuf: ^6.0.0
  threshold:
    path: ../threshold
  server: # Depend on server for generated protos
    path: ../server 

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
