name: threshold
description: A Dart library for implementing threshold cryptography, specifically focusing on Distributed Key Generation (DKG) protocols based on secp256k1 elliptic curves.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.2

# Add regular dependencies here.
dependencies:
  secp256k1: ^0.3.0
  crypto: ^3.0.3
  convert: ^3.1.1
  pointycastle: ^3.7.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
