name: e2e
description: End-to-End tests for MPC Wallet
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  client:
    path: ../client
  server:
    path: ../server
  threshold:
    path: ../threshold
  protocol:
    path: ../protocol
  grpc: ^5.1.0
  protobuf: ^6.0.0
  http: ^1.2.0
  bitcoin_base: ^7.0.0
  blockchain_utils: ^5.4.0
  hive: ^2.2.3

dev_dependencies:
  test: ^1.24.0
